name: CI

# Déclenchement du workflow sur un push ou une pull request vers la branche principale
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    # Le job est exécuté sur la dernière version d'Ubuntu
    runs-on: ubuntu-latest

    steps:
    # Étape 1: Vérification du code source
    - name: Check out code
      uses: actions/checkout@v2

    # Étape 2: Configuration de Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    # Étape 3: Installation des dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_main.txt

    # Étape 4: Exécution des tests
    - name: Run tests
      run: |
        python -m unittest discover -s tests